homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include customize.yaml
  packages: !include_dir_named packages


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:

config:

http:
  api_password: !secret ha_http_password

updater:

discovery:

conversation:

history:

logbook:

map:

