homeassistant:
  name: ${name-home}
  latitude: ${latitude-39.929986}
  longitude: ${longitude-116.395645}
  elevation: ${elevation-0}
  unit_system: metric
  time_zone: ${time_zone-Asia/Shanghai}
  customize: !include customize.yaml
  packages: !include_dir_named packages


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:

config:

http:
  api_password: !secret ha_http_password

updater:

discovery:

conversation:

history:

logbook:

map:

